spring.application.name=anime-ecommerce-backend

#PostgreSQL connection

spring.datasource.url=jdbc:postgresql://localhost:5432/animestore
spring.datasource.username=postgres
spring.datasource.password=nha@232007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
