spring.application.name=anime-ecommerce-backend

#PostgreSQL connection

spring.datasource.url=jdbc:postgresql://localhost:5432/animestore
spring.datasource.username=postgres
spring.datasource.password=nha@232007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Cloudinary

cloudinary.cloud-name=a7dmai3z
cloudinary.api-key=453224851548537
cloudinary.api-secret=szWL_1-CE3_x4FcK07hveY6iY6I
